In [2]:
import numpy as np
import pandas as pd
import cvxpy as cp
import itertools
import matplotlib.pyplot as plt

# from utils_opt import *

%load_ext autoreload
%autoreload 2

# Test active learning approach

In [3]:
# make fake data
n, d = 100, 5
Sigma = np.random.normal(size=(d, d))
Sigma = Sigma.T @ Sigma
mu = np.random.normal(size=d)
# assume moving average system
X = np.random.multivariate_normal(mean=mu, cov=Sigma, size=n)

beta = np.random.normal(size=d)
f = X@beta + np.random.normal(size=n)

In [4]:
k = 7
Xk = X[:k]

In [5]:
# covariance matrix
K = np.array([np.diagonal((Xk[i] - Xk) @ (Xk[i] - Xk).T) for i in range(k)])
K = np.exp(-0.5*K)
K_inv = np.linalg.inv(K)

In [6]:
# b matrix
normsqs = 0.5*np.diagonal(Xk @ Xk.T)
B = np.array([np.log(K[i]) + normsqs[i] + normsqs for i in range(k)])

# m tensor
M = np.array([Xk[i] + Xk for i in range(k)])

In [7]:
x = cp.Variable(d)
y = cp.hstack([cp.exp(-(1/2)*((x - Xk[i]).T @ (x - Xk[i]))) for i in range(k)])
obj = cp.log(cp.quad_form(y, K_inv))

In [12]:
cp.vstack([cp.exp(-1*(cp.quad_form(x, np.identity(d)) + x.T @ M[i,j] - B[i,j])) for i in range(k) for j in range(k)])

Expression(UNKNOWN, NONNEGATIVE, (49, 1))

In [265]:
obj = cp.log(cp.sum(cp.exp(-cp.vstack([cp.quad_form(x, np.identity(d)) + x.T @ M[i,j] - B[i,j] for i in range(k) for j in range(k)]))))

In [266]:
# problem
prob = cp.Problem(cp.Maximize(obj))
prob.solve(solver='SCS')

DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
exp(-Vstack(QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 1.58130646 -0.7423973  -3.98291009 -6.6476665   6.0118778 ] + -24.81235029671911, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 2.31031818e+00  6.39634169e-03 -3.25687260e+00 -7.05627328e+00
  4.67411933e+00] + -24.57768179958472, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.80731051 -1.34159983 -6.72087419 -5.06391457  3.83343481] + -37.60121047664949, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 1.85402294  0.53096919 -6.11836484 -6.31170487  4.38552341] + -31.816464654127717, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 0.04682715 -1.40985365 -2.80580261 -6.36056257  4.93642001] + -22.740410428267403, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-1.26456334 -2.07649234 -4.16871846 -6.05281732  5.444008  ] + -30.33296693614291, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-1.62517764 -2.19886826 -3.59501236 -5.63595443  4.7443838 ] + -30.055935620438966, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 2.31031818e+00  6.39634169e-03 -3.25687260e+00 -7.05627328e+00
  4.67411933e+00] + -24.57768179958472, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 3.03932991  0.75518999 -2.53083511 -7.46488005  3.33636086] + -20.767175627321336, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.07829879 -0.59280618 -5.9948367  -5.47252134  2.49567633] + -39.27731658985562, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 2.58303467  1.27976283 -5.39232735 -6.72031165  3.04776494] + -29.9415209596989, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 0.77583887 -0.66106001 -2.07976512 -6.76916935  3.59866154] + -21.948168103257682, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.53555162 -1.32769869 -3.44268097 -6.46142409  4.10624953] + -32.790223388221996, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.89616591 -1.45007461 -2.86897487 -6.04456121  3.40662533] + -31.68559109775575, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.80731051 -1.34159983 -6.72087419 -5.06391457  3.83343481] + -37.60121047664949, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.07829879 -0.59280618 -5.9948367  -5.47252134  2.49567633] + -39.27731658985562, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-3.19592749 -1.94080235 -9.45883829 -3.48016264  1.65499181] + -29.575204476664094, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.53459403 -0.06823334 -8.85632894 -4.72795294  2.20708042] + -36.09794581772811, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-2.34178983 -2.00905618 -5.54376671 -4.77681064  2.75797702] + -31.889398871547776, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-3.65318032 -2.67569486 -6.90668256 -4.46906538  3.265565  ] + -32.83683889734873, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-4.01379461 -2.79807078 -6.33297646 -4.0522025   2.56594081] + -31.011598101778304, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 1.85402294  0.53096919 -6.11836484 -6.31170487  4.38552341] + -31.816464654127717, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 2.58303467  1.27976283 -5.39232735 -6.72031165  3.04776494] + -29.9415209596989, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.53459403 -0.06823334 -8.85632894 -4.72795294  2.20708042] + -36.09794581772811, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 2.12673942  1.80433568 -8.2538196  -5.97574325  2.75916902] + -29.80667669424266, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 0.31954363 -0.13648716 -4.94125737 -6.02460094  3.31006562] + -31.68104749278322, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.99184686 -0.80312585 -6.30417322 -5.71685569  3.81765361] + -38.29179938722842, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-1.35246115 -0.92550177 -5.73046711 -5.29999281  3.11802941] + -38.21617954550699, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 0.04682715 -1.40985365 -2.80580261 -6.36056257  4.93642001] + -22.740410428267403, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 0.77583887 -0.66106001 -2.07976512 -6.76916935  3.59866154] + -21.948168103257682, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-2.34178983 -2.00905618 -5.54376671 -4.77681064  2.75797702] + -31.889398871547776, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [ 0.31954363 -0.13648716 -4.94125737 -6.02460094  3.31006562] + -31.68104749278322, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-1.48765217 -2.07731    -1.62869514 -6.07345864  3.86096223] + -15.243725700299409, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-2.79904266 -2.74394868 -2.99161099 -5.76571338  4.36855021] + -22.440861419378663, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-3.15965695 -2.8663246  -2.41790489 -5.3488505   3.66892602] + -19.981381347367122, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-1.26456334 -2.07649234 -4.16871846 -6.05281732  5.444008  ] + -30.33296693614291, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.53555162 -1.32769869 -3.44268097 -6.46142409  4.10624953] + -32.790223388221996, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-3.65318032 -2.67569486 -6.90668256 -4.46906538  3.265565  ] + -32.83683889734873, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.99184686 -0.80312585 -6.30417322 -5.71685569  3.81765361] + -38.29179938722842, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-2.79904266 -2.74394868 -2.99161099 -5.76571338  4.36855021] + -22.440861419378663, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-4.11043315 -3.41058737 -4.35452684 -5.45796813  4.8761382 ] + -25.263952669924464, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-4.47104744 -3.53296329 -3.78082073 -5.04110525  4.176514  ] + -23.258732325047895, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-1.62517764 -2.19886826 -3.59501236 -5.63595443  4.7443838 ] + -30.055935620438966, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-0.89616591 -1.45007461 -2.86897487 -6.04456121  3.40662533] + -31.68559109775575, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-4.01379461 -2.79807078 -6.33297646 -4.0522025   2.56594081] + -31.011598101778304, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-1.35246115 -0.92550177 -5.73046711 -5.29999281  3.11802941] + -38.21617954550699, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-3.15965695 -2.8663246  -2.41790489 -5.3488505   3.66892602] + -19.981381347367122, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-4.47104744 -3.53296329 -3.78082073 -5.04110525  4.176514  ] + -23.258732325047895, QuadForm(var23113, [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]) + var23113 @ [-4.83166173 -3.65533921 -3.20711463 -4.62424237  3.47688981] + -20.11610607952605))

In [212]:
# objective function
quad_array = [-cp.quad_form(x, np.identity(d)) + x.T @ M[i,j] - B[i,j] for i in range(k) for j in range(k)]
quad_array = cp.vstack(quad_array)

# obj = cp.log(1 - cp.quad_form(x, np.identity(d)) * 
# obj = cp.exp(cp.quad_form(x, np.identity(d)))*cp.sum(cp.exp(quad_array))
obj = cp.log_sum_exp(quad_array)

In [144]:
quad_array

Expression(CONVEX, UNKNOWN, (1, 49))

In [94]:
x.T @ M

ValueError: Expressions of dimension greater than 2 are not supported.